'use client'

import * as React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'
import { Textarea } from '@/components/ui/textarea'
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Plus,
  Clock,
  CheckCircle2,
  MoreHorizontal,
  Heart,
  AlertTriangle,
  CreditCard,
  User,
  Filter,
} from 'lucide-react'

interface Task {
  id: string
  title: string
  description?: string
  taskType: 'thank_you' | 'follow_up' | 'failed_payment' | 'card_expiring' | 'at_risk' | 'custom'
  donorName?: string
  dueDate?: string
  priority: 'low' | 'medium' | 'high'
  status: 'pending' | 'completed' | 'dismissed'
  autoGenerated: boolean
}

const tasks: Task[] = [
  { id: 't1', title: 'Thank David Brown for first gift', description: 'Send a personal thank you for their $250 gift', taskType: 'thank_you', donorName: 'David Brown', dueDate: '2024-12-15', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't2', title: 'Welcome Amanda Lee', description: 'Reach out to new supporter Amanda', taskType: 'thank_you', donorName: 'Amanda Lee', dueDate: '2024-12-17', priority: 'high', status: 'pending', autoGenerated: true },
  { id: 't3', title: 'Follow up with Jennifer Davis', description: 'At-risk donor - no gift in 6 months', taskType: 'at_risk', donorName: 'Jennifer Davis', dueDate: '2024-12-20', priority: 'medium', status: 'pending', autoGenerated: true },
  { id: 't4', title: 'Rebecca card expiring soon', description: 'Card expires 6/2025 - remind to update', taskType: 'card_expiring', donorName: 'Rebecca Johnson', dueDate: '2025-05-01', priority: 'low', status: 'pending', autoGenerated: true },
  { id: 't5', title: 'Send December newsletter', description: 'Monthly update to all supporters', taskType: 'custom', dueDate: '2024-12-18', priority: 'medium', status: 'pending', autoGenerated: false },
  { id: 't6', title: 'Thank Thomas Smith', description: 'Sent thank you email', taskType: 'thank_you', donorName: 'Thomas Smith', priority: 'high', status: 'completed', autoGenerated: true },
]

const taskTypeConfig = {
  thank_you: { label: 'Thank You', icon: Heart, color: 'text-[#5d7052] bg-[#e8ebe5]' },
  follow_up: { label: 'Follow Up', icon: User, color: 'text-blue-600 bg-blue-50' },
  failed_payment: { label: 'Failed Payment', icon: AlertTriangle, color: 'text-red-600 bg-red-50' },
  card_expiring: { label: 'Card Expiring', icon: CreditCard, color: 'text-amber-600 bg-amber-50' },
  at_risk: { label: 'At Risk', icon: AlertTriangle, color: 'text-orange-600 bg-orange-50' },
  custom: { label: 'Custom', icon: CheckCircle2, color: 'text-gray-600 bg-gray-100' },
}

function TaskRow({ task, onComplete }: { task: Task; onComplete: () => void }) {
  const typeConfig = taskTypeConfig[task.taskType]
  const Icon = typeConfig.icon
  const isOverdue = task.dueDate && new Date(task.dueDate) < new Date() && task.status === 'pending'
  const isDueToday = task.dueDate && new Date(task.dueDate).toDateString() === new Date().toDateString()

  return (
    <div className={`flex items-start gap-4 p-4 border rounded-lg ${task.status === 'completed' ? 'opacity-50' : ''}`}>
      <Checkbox
        checked={task.status === 'completed'}
        onCheckedChange={() => onComplete()}
        className="mt-1"
      />
      
      <div className={`flex h-9 w-9 items-center justify-center rounded-lg shrink-0 ${typeConfig.color}`}>
        <Icon className="h-4 w-4" />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <p className={`font-medium ${task.status === 'completed' ? 'line-through' : ''}`}>{task.title}</p>
          {task.priority === 'high' && <div className="h-2 w-2 rounded-full bg-red-500" />}
          {task.priority === 'medium' && <div className="h-2 w-2 rounded-full bg-amber-500" />}
        </div>
        {task.description && (
          <p className="text-sm text-muted-foreground mt-0.5">{task.description}</p>
        )}
        <div className="flex items-center gap-3 mt-2">
          {task.donorName && (
            <span className="text-xs flex items-center gap-1 text-muted-foreground">
              <User className="h-3 w-3" />
              {task.donorName}
            </span>
          )}
          {task.dueDate && (
            <span className={`text-xs flex items-center gap-1 ${isOverdue ? 'text-red-600 font-medium' : isDueToday ? 'text-amber-600 font-medium' : 'text-muted-foreground'}`}>
              <Clock className="h-3 w-3" />
              {isOverdue ? 'Overdue' : isDueToday ? 'Due today' : new Date(task.dueDate).toLocaleDateString()}
            </span>
          )}
        </div>
      </div>

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="icon" className="h-8 w-8 shrink-0">
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          <DropdownMenuItem onClick={onComplete}>
            <CheckCircle2 className="mr-2 h-4 w-4" />
            {task.status === 'completed' ? 'Mark Incomplete' : 'Mark Complete'}
          </DropdownMenuItem>
          {task.donorName && (
            <DropdownMenuItem>
              <User className="mr-2 h-4 w-4" />
              View Donor
            </DropdownMenuItem>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

function NewTaskDialog() {
  const [open, setOpen] = React.useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button className="bg-[#5d7052] hover:bg-[#4a5a42] text-white">
          <Plus className="mr-2 h-4 w-4" />
          Add Task
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create New Task</DialogTitle>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">Task Title</label>
            <Input placeholder="e.g., Send thank you to John" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">Description (optional)</label>
            <Textarea placeholder="Add any notes or details..." className="resize-none" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Due Date</label>
              <Input type="date" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Priority</label>
              <Select defaultValue="medium">
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
        </div>
        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
          <Button className="bg-[#5d7052] hover:bg-[#4a5a42] text-white" onClick={() => setOpen(false)}>Create Task</Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

export default function TasksPage() {
  const [taskList, setTaskList] = React.useState(tasks)
  const [filter, setFilter] = React.useState<'all' | 'pending' | 'completed'>('pending')

  const handleComplete = (taskId: string) => {
    setTaskList(prev => prev.map(t => 
      t.id === taskId ? { ...t, status: t.status === 'completed' ? 'pending' : 'completed' as const } : t
    ))
  }

  const filteredTasks = taskList.filter(task => {
    if (task.status === 'dismissed') return false
    if (filter === 'pending' && task.status !== 'pending') return false
    if (filter === 'completed' && task.status !== 'completed') return false
    return true
  }).sort((a, b) => {
    if (a.status === 'completed' && b.status !== 'completed') return 1
    if (a.status !== 'completed' && b.status === 'completed') return -1
    if (a.priority === 'high' && b.priority !== 'high') return -1
    if (a.priority !== 'high' && b.priority === 'high') return 1
    return 0
  })

  const pendingCount = taskList.filter(t => t.status === 'pending').length
  const completedCount = taskList.filter(t => t.status === 'completed').length

  return (
    <div className="p-6">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl font-semibold">Tasks</h1>
          <p className="text-muted-foreground">Manage your follow-up tasks and to-dos.</p>
        </div>
        <NewTaskDialog />
      </div>

      <div className="flex items-center justify-between mb-4">
        <Tabs value={filter} onValueChange={(v) => setFilter(v as typeof filter)} className="w-auto">
          <TabsList className="bg-transparent border p-1">
            <TabsTrigger value="all" className="data-[state=active]:bg-muted">All</TabsTrigger>
            <TabsTrigger value="pending" className="data-[state=active]:bg-muted">
              Pending ({pendingCount})
            </TabsTrigger>
            <TabsTrigger value="completed" className="data-[state=active]:bg-muted">
              Completed ({completedCount})
            </TabsTrigger>
          </TabsList>
        </Tabs>
        <Button variant="outline" size="sm">
          <Filter className="h-4 w-4 mr-2" />
          Filter
        </Button>
      </div>

      <div className="space-y-3">
        {filteredTasks.length > 0 ? (
          filteredTasks.map(task => (
            <TaskRow 
              key={task.id} 
              task={task} 
              onComplete={() => handleComplete(task.id)}
            />
          ))
        ) : (
          <Card className="border">
            <CardContent className="p-8 text-center">
              <CheckCircle2 className="h-12 w-12 mx-auto text-[#5d7052] mb-4" />
              <h3 className="font-medium mb-1">All caught up!</h3>
              <p className="text-sm text-muted-foreground">No pending tasks. Great job staying on top of your follow-ups!</p>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  )
}