'use client'

import * as React from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { Checkbox } from '@/components/ui/checkbox'
import { Textarea } from '@/components/ui/textarea'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import {
  Plus,
  Clock,
  CheckCircle2,
  AlertCircle,
  MoreHorizontal,
  Heart,
  AlertTriangle,
  CreditCard,
  Calendar,
  User,
  Mail,
  Phone,
  Trash2,
  Sparkles,
  Filter,
} from 'lucide-react'

interface Task {
  id: string
  title: string
  description?: string
  taskType: 'thank_you' | 'follow_up' | 'failed_payment' | 'card_expiring' | 'at_risk' | 'custom'
  donorName?: string
  donorId?: string
  dueDate?: string
  priority: 'low' | 'medium' | 'high'
  status: 'pending' | 'completed' | 'dismissed'
  autoGenerated: boolean
  createdAt: string
}

const tasks: Task[] = [
  { id: 't1', title: 'Thank David Brown for first gift', description: 'Send a personal thank you for their $250 gift', taskType: 'thank_you', donorName: 'David Brown', donorId: 'd5', dueDate: '2024-12-15', priority: 'high', status: 'pending', autoGenerated: true, createdAt: '2024-12-12' },
  { id: 't2', title: 'Welcome Amanda Lee', description: 'Reach out to new supporter Amanda', taskType: 'thank_you', donorName: 'Amanda Lee', donorId: 'd8', dueDate: '2024-12-17', priority: 'high', status: 'pending', autoGenerated: true, createdAt: '2024-12-14' },
  { id: 't3', title: 'Follow up with Jennifer Davis', description: 'At-risk donor - no gift in 6 months', taskType: 'at_risk', donorName: 'Jennifer Davis', donorId: 'd4', dueDate: '2024-12-20', priority: 'medium', status: 'pending', autoGenerated: true, createdAt: '2024-12-01' },
  { id: 't4', title: 'Rebecca card expiring soon', description: 'Card expires 6/2025 - remind to update', taskType: 'card_expiring', donorName: 'Rebecca Johnson', donorId: 'd2', dueDate: '2025-05-01', priority: 'low', status: 'pending', autoGenerated: true, createdAt: '2024-12-01' },
  { id: 't5', title: 'Send December newsletter', description: 'Monthly update to all supporters', taskType: 'custom', dueDate: '2024-12-18', priority: 'medium', status: 'pending', autoGenerated: false, createdAt: '2024-12-10' },
  { id: 't6', title: 'Thank Thomas Smith', description: 'Sent thank you email', taskType: 'thank_you', donorName: 'Thomas Smith', donorId: 'd1', priority: 'high', status: 'completed', autoGenerated: true, createdAt: '2024-12-08' },
]

const taskTypeConfig = {
  thank_you: { label: 'Thank You', icon: Heart, color: 'text-rose-600 bg-rose-100 dark:bg-rose-950' },
  follow_up: { label: 'Follow Up', icon: User, color: 'text-blue-600 bg-blue-100 dark:bg-blue-950' },
  failed_payment: { label: 'Failed Payment', icon: AlertCircle, color: 'text-red-600 bg-red-100 dark:bg-red-950' },
  card_expiring: { label: 'Card Expiring', icon: CreditCard, color: 'text-amber-600 bg-amber-100 dark:bg-amber-950' },
  at_risk: { label: 'At Risk', icon: AlertTriangle, color: 'text-orange-600 bg-orange-100 dark:bg-orange-950' },
  custom: { label: 'Custom', icon: Sparkles, color: 'text-purple-600 bg-purple-100 dark:bg-purple-950' },
}

const priorityConfig = {
  high: { label: 'High', color: 'bg-rose-500' },
  medium: { label: 'Medium', color: 'bg-amber-500' },
  low: { label: 'Low', color: 'bg-blue-500' },
}

function TaskRow({ task, onComplete, onDismiss }: { task: Task; onComplete: () => void; onDismiss: () => void }) {
  const typeConfig = taskTypeConfig[task.taskType]
  const Icon = typeConfig.icon
  const isOverdue = task.dueDate && new Date(task.dueDate) < new Date() && task.status === 'pending'
  const isDueToday = task.dueDate && new Date(task.dueDate).toDateString() === new Date().toDateString()

  return (
    <div className={`flex items-start gap-4 p-4 border-b last:border-0 hover:bg-muted/50 transition-colors ${task.status === 'completed' ? 'opacity-60' : ''}`}>
      <Checkbox
        checked={task.status === 'completed'}
        onCheckedChange={() => onComplete()}
        className="mt-1"
      />
      
      <div className={`flex h-9 w-9 items-center justify-center rounded-lg ${typeConfig.color}`}>
        <Icon className="h-4 w-4" />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <p className={`font-medium ${task.status === 'completed' ? 'line-through' : ''}`}>{task.title}</p>
          <div className={`h-2 w-2 rounded-full ${priorityConfig[task.priority].color}`} />
        </div>
        {task.description && (
          <p className="text-sm text-muted-foreground mt-0.5">{task.description}</p>
        )}
        <div className="flex items-center gap-3 mt-2">
          {task.donorName && (
            <span className="text-xs flex items-center gap-1 text-muted-foreground">
              <User className="h-3 w-3" />
              {task.donorName}
            </span>
          )}
          {task.dueDate && (
            <span className={`text-xs flex items-center gap-1 ${isOverdue ? 'text-rose-600 font-medium' : isDueToday ? 'text-amber-600 font-medium' : 'text-muted-foreground'}`}>
              <Clock className="h-3 w-3" />
              {isOverdue ? 'Overdue' : isDueToday ? 'Due today' : new Date(task.dueDate).toLocaleDateString()}
            </span>
          )}
          {task.autoGenerated && (
            <Badge variant="secondary" className="text-[10px] px-1.5 py-0">Auto</Badge>
          )}
        </div>
      </div>

      {task.status === 'pending' && task.donorName && (
        <div className="hidden md:flex gap-1">
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <Mail className="h-4 w-4" />
          </Button>
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <Phone className="h-4 w-4" />
          </Button>
        </div>
      )}

      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant="ghost" size="icon" className="h-8 w-8">
            <MoreHorizontal className="h-4 w-4" />
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end">
          {task.status === 'pending' && (
            <>
              <DropdownMenuItem onClick={onComplete}>
                <CheckCircle2 className="mr-2 h-4 w-4" />
                Mark Complete
              </DropdownMenuItem>
              <DropdownMenuItem onClick={onDismiss}>
                <Trash2 className="mr-2 h-4 w-4" />
                Dismiss
              </DropdownMenuItem>
            </>
          )}
          {task.donorName && (
            <DropdownMenuItem>
              <User className="mr-2 h-4 w-4" />
              View Donor
            </DropdownMenuItem>
          )}
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  )
}

function NewTaskDialog() {
  const [open, setOpen] = React.useState(false)

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="mr-2 h-4 w-4" />
          Add Task
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Create New Task</DialogTitle>
          <DialogDescription>Add a follow-up task for your ministry.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 py-4">
          <div className="space-y-2">
            <label className="text-sm font-medium">Task Title</label>
            <Input placeholder="e.g., Send thank you to John" />
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">Description (optional)</label>
            <Textarea placeholder="Add any notes or details..." className="resize-none" />
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Due Date</label>
              <Input type="date" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Priority</label>
              <Select defaultValue="medium">
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>
          <div className="space-y-2">
            <label className="text-sm font-medium">Link to Donor (optional)</label>
            <Select>
              <SelectTrigger>
                <SelectValue placeholder="Select a donor..." />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="d1">Thomas Smith</SelectItem>
                <SelectItem value="d2">Rebecca Johnson</SelectItem>
                <SelectItem value="d3">Michael Williams</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>
        <div className="flex justify-end gap-2">
          <Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
          <Button onClick={() => setOpen(false)}>Create Task</Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}

export default function TasksPage() {
  const [taskList, setTaskList] = React.useState(tasks)
  const [filter, setFilter] = React.useState<'all' | 'pending' | 'completed'>('pending')
  const [typeFilter, setTypeFilter] = React.useState<string>('all')

  const handleComplete = (taskId: string) => {
    setTaskList(prev => prev.map(t => 
      t.id === taskId ? { ...t, status: t.status === 'completed' ? 'pending' : 'completed' as const } : t
    ))
  }

  const handleDismiss = (taskId: string) => {
    setTaskList(prev => prev.map(t => 
      t.id === taskId ? { ...t, status: 'dismissed' as const } : t
    ))
  }

  const filteredTasks = taskList.filter(task => {
    if (task.status === 'dismissed') return false
    if (filter === 'pending' && task.status !== 'pending') return false
    if (filter === 'completed' && task.status !== 'completed') return false
    if (typeFilter !== 'all' && task.taskType !== typeFilter) return false
    return true
  }).sort((a, b) => {
    if (a.status === 'completed' && b.status !== 'completed') return 1
    if (a.status !== 'completed' && b.status === 'completed') return -1
    if (a.priority === 'high' && b.priority !== 'high') return -1
    if (a.priority !== 'high' && b.priority === 'high') return 1
    return 0
  })

  const pendingCount = taskList.filter(t => t.status === 'pending').length
  const completedCount = taskList.filter(t => t.status === 'completed').length
  const overdueCount = taskList.filter(t => t.status === 'pending' && t.dueDate && new Date(t.dueDate) < new Date()).length

  return (
    <div className="space-y-6 p-4 md:p-6 lg:p-8">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Tasks</h1>
          <p className="text-muted-foreground">Manage your follow-up tasks and to-dos.</p>
        </div>
        <NewTaskDialog />
      </div>

      <div className="grid gap-4 md:grid-cols-4">
        <Card className="cursor-pointer hover:border-primary/50" onClick={() => setFilter('pending')}>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-blue-100 dark:bg-blue-950 flex items-center justify-center">
              <Clock className="h-5 w-5 text-blue-600" />
            </div>
            <div>
              <p className="text-2xl font-bold">{pendingCount}</p>
              <p className="text-xs text-muted-foreground">Pending</p>
            </div>
          </CardContent>
        </Card>
        <Card className="cursor-pointer hover:border-emerald-500/50" onClick={() => setFilter('completed')}>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-emerald-100 dark:bg-emerald-950 flex items-center justify-center">
              <CheckCircle2 className="h-5 w-5 text-emerald-600" />
            </div>
            <div>
              <p className="text-2xl font-bold">{completedCount}</p>
              <p className="text-xs text-muted-foreground">Completed</p>
            </div>
          </CardContent>
        </Card>
        <Card className={`${overdueCount > 0 ? 'border-rose-200 dark:border-rose-900/50' : ''}`}>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-rose-100 dark:bg-rose-950 flex items-center justify-center">
              <AlertCircle className="h-5 w-5 text-rose-600" />
            </div>
            <div>
              <p className="text-2xl font-bold">{overdueCount}</p>
              <p className="text-xs text-muted-foreground">Overdue</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4 flex items-center gap-3">
            <div className="h-10 w-10 rounded-full bg-amber-100 dark:bg-amber-950 flex items-center justify-center">
              <Calendar className="h-5 w-5 text-amber-600" />
            </div>
            <div>
              <p className="text-2xl font-bold">{taskList.filter(t => t.status === 'pending' && t.dueDate && new Date(t.dueDate).toDateString() === new Date().toDateString()).length}</p>
              <p className="text-xs text-muted-foreground">Due Today</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader className="pb-4">
          <div className="flex flex-col md:flex-row gap-4">
            <div className="flex gap-2">
              <Button 
                variant={filter === 'all' ? 'default' : 'outline'} 
                size="sm"
                onClick={() => setFilter('all')}
              >
                All
              </Button>
              <Button 
                variant={filter === 'pending' ? 'default' : 'outline'} 
                size="sm"
                onClick={() => setFilter('pending')}
              >
                Pending
              </Button>
              <Button 
                variant={filter === 'completed' ? 'default' : 'outline'} 
                size="sm"
                onClick={() => setFilter('completed')}
              >
                Completed
              </Button>
            </div>
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-[160px]">
                <Filter className="h-4 w-4 mr-2" />
                <SelectValue placeholder="Task type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                <SelectItem value="thank_you">Thank You</SelectItem>
                <SelectItem value="at_risk">At Risk</SelectItem>
                <SelectItem value="card_expiring">Card Expiring</SelectItem>
                <SelectItem value="custom">Custom</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {filteredTasks.length > 0 ? (
            <div>
              {filteredTasks.map(task => (
                <TaskRow 
                  key={task.id} 
                  task={task} 
                  onComplete={() => handleComplete(task.id)}
                  onDismiss={() => handleDismiss(task.id)}
                />
              ))}
            </div>
          ) : (
            <div className="p-8 text-center">
              <CheckCircle2 className="h-12 w-12 mx-auto text-emerald-500 mb-4" />
              <h3 className="font-medium mb-1">All caught up!</h3>
              <p className="text-sm text-muted-foreground">No pending tasks. Great job staying on top of your follow-ups!</p>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
